# Generated by Django 2.1.2 on 2018-10-31 11:12

from django.db import migrations
import imagekit.models.fields
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=user.models.get_profile_photo_path),
        ),
    ]
